server:
  port: 8082

spring:
  application:
    name: quran-service
  datasource:
    url: jdbc:mysql://mysql:3306/quran_db?useSSL=false&allowPublicKeyRetrieval=true
    username: quran_user
    password: quran_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 